#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("NfcXample.Resource", IsApplication=true)]

namespace NfcXample
{
	
	
	[global::System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7F010000
			public const int cornelius = 2130771968;
			
			// aapt resource value: 0x7F010001
			public const int dr_zaius = 2130771969;
			
			// aapt resource value: 0x7F010002
			public const int gorillas = 2130771970;
			
			// aapt resource value: 0x7F010003
			public const int heston = 2130771971;
			
			// aapt resource value: 0x7F010004
			public const int icon = 2130771972;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7F020000
			public const int ape_view = 2130837504;
			
			// aapt resource value: 0x7F020001
			public const int back_to_main_activity = 2130837505;
			
			// aapt resource value: 0x7F020002
			public const int read_nfc_text_view = 2130837506;
			
			// aapt resource value: 0x7F020003
			public const int text_view = 2130837507;
			
			// aapt resource value: 0x7F020004
			public const int write_tag_button = 2130837508;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7F030000
			public const int DisplayHominid = 2130903040;
			
			// aapt resource value: 0x7F030001
			public const int Main = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7F040000
			public const int app_name = 2130968576;
			
			// aapt resource value: 0x7F040001
			public const int button_back_to_main_activity = 2130968577;
			
			// aapt resource value: 0x7F040002
			public const int button_write_nfc = 2130968578;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
